# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Foto',
            field=models.ImageField(blank=True, default='', upload_to='users/%Y/%m/%d'),
        ),
    ]
