# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen_anuncio',
            name='imagen_anuncio',
            field=models.FileField(upload_to='productos/%Y/%m/%d'),
        ),
    ]
