# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='replied',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='respuesta',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
