# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170413_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen_anuncio',
            old_name='Anuncio',
            new_name='anuncio_imagen_fk',
        ),
    ]
