# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170227_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_principal',
            field=models.ImageField(default=datetime.datetime(2017, 2, 27, 20, 14, 25, 217879, tzinfo=utc), upload_to='productos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_secundaria',
            field=models.ImageField(default=datetime.datetime(2017, 2, 27, 20, 14, 32, 250771, tzinfo=utc), upload_to='productos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_terciaria',
            field=models.ImageField(default=datetime.datetime(2017, 2, 27, 20, 14, 38, 504558, tzinfo=utc), upload_to='productos'),
            preserve_default=False,
        ),
    ]
