# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170228_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='Moneda',
            field=models.CharField(blank=True, choices=[('mxn', 'MXN'), ('usd', 'USD')], default='Moneda de cambio', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Categoria_Anuncio'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='descripcion_anuncio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='fecha_anuncio',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_terciaria',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='subcategoria_relacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.SubCategoria_Anuncio'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo_anuncio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to=settings.AUTH_USER_MODEL),
        ),
    ]
