# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170228_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to=settings.AUTH_USER_MODEL),
        ),
    ]
