# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170228_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='descripcion_anuncio',
            field=models.TextField(),
        ),
    ]
