# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20170228_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Categoria_Anuncio'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='fecha_anuncio',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='subcategoria_relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SubCategoria_Anuncio'),
        ),
    ]
