# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20170302_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_principal',
            field=models.ImageField(upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_secundaria',
            field=models.ImageField(upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_terciaria',
            field=models.ImageField(upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
