# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20170302_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_opcional_dos',
            field=models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_opcional_tres',
            field=models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_opcional_uno',
            field=models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_principal',
            field=models.ImageField(upload_to='productos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_secundaria',
            field=models.ImageField(upload_to='productos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_terciaria',
            field=models.ImageField(upload_to='productos/%Y/%m/%d'),
        ),
    ]
