# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20170302_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='products.Anuncio'),
        ),
    ]
