# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='cuerpo',
            new_name='pregunta',
        ),
        migrations.AlterField(
            model_name='answer',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_comentario', to='products.Comment'),
        ),
    ]
